# Author: Haniye Kashgarani
# Affiliation: University of Wyoming
# Date: 2023-08-17T15:39:37+00:00
# Github: haniyeka

name: aslib_data_check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build_Makefile:
    runs-on: ubuntu-latest
    container:
      # Docker image that includes python2.7, and libraries like liac-arff, pyyaml, and typing
      # This docker also includes files from https://github.com/coseal/aslib-spec/tree/master/data_check_tool_python in /usr/src/app/data_check_tool_python
      image: haniyeka/aslib_data_check:latest
    steps:
    - uses: actions/checkout@v3

    - name: Navigate to data_check_tool_python and run the script for all the scenarios
      run: |
        echo "Current directory:"
        echo $(pwd)
        ls
        cd /usr/src/app/data_check_tool_python 
